config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  resources :characters, only: [:index, :new, :create, :show] do
    resources :levels, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user
  belongs_to :race
  has_many :levels

  validates :name, presence: true, length: { minimum: 3, maximum: 30 }
  validates :description, length: { maximum: 500 }

  def level
    levels.count
  end

  def class_levels
    class_levels_hash = {}

    levels.each do |level|
      class_hash = { base: level.base_class, sub: level.sub_class }
      class_levels_hash[class_hash].nil? ? class_levels_hash[class_hash] = 1 : class_levels_hash[class_hash] += 1
    end

    class_levels_hash
  end
end

app/models/level.rb
class Level < ApplicationRecord
  belongs_to :character

  validates :character, :base_class, presence: true
end

app/models/race.rb
class Race < ApplicationRecord
  has_many :characters
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :characters, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  # before_action :authenticate_user!, only: [:new, :create]

  def index
    @characters = Character.all
  end

  def new
    @character = Character.new
  end

  def create
    @character = current_user.characters.create(character_params)
    redirect_to characters_path
  end

  def show
  end

  private

  def character_params
    params.require(:character).permit(:name, :character_class, :race, :level)
  end

  helper_method :current_character

  def current_character
    @current_character ||= Character.find(params[:id])
  end
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  # before_action :authenticate_user!, only: [:new, :create]

  def new
    @level = Level.new
  end

  def create
    @level = current_character.levels.create(level_params)
    if @level.valid?
      redirect_to character_path(current_character)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  helper_method :current_character

  def current_character
    @current_character ||= Character.find(params[:character_id])
  end

  def level_params
    params.require(:level).permit(:base_class, :sub_class)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(type)
    case type
    when 'error' then 'alert-danger'
    when 'notice' then 'alert-info'
    when 'alert' then 'alert-warning'
    when 'success' then 'alert-success'
    else type.to_s
    end
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/application/_flash_messages.html.erb
<div class="container">
  <% flash.each do |type, message| %>
    <div class="alert <%= flash_class(type.to_s) %> alert-dismissible fade show" role="alert">
       <button type="button" class="close" data-dismiss="alert" aria-label="Close">
         <span aria-hidden="true">&times;</span>
       </button>
       <span><%= message %></span>
    </div>
  <% end %>
</div>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-toggleable-sm navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Clerical Errors</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="navbar-nav mr-auto">
      <%= link_to "Character Generator", characters_path, class: 'nav-item nav-link' %>
    </div>
    <div class="navbar-nav pull-md-right">
      <% if current_user %>
        <div class="nav-item dropdown">
          <a href="#" class="nav-item nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %></a>
          <div class="dropdown-menu" aria-labelledby="Preview">
            <%= link_to "My Profile", '#', class: 'dropdown-item' %>
            <%= link_to "Edit Account", edit_user_registration_path, class: 'dropdown-item' %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </div>
      <% else %>
        <%= link_to "Create Account", new_user_registration_path, class: 'nav-item nav-link' %>
        <%= link_to "Sign In", new_user_session_path, class: 'nav-item nav-link' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/characters/index.html.erb
<div class="container">
  <div class="row">
    <div class="col col-xs-auto text-center">
      <h1>Characters</h1>
      <h2><%= link_to "Create New Character", new_character_path %></h2>
    </div>
  </div>
  <hr />
  <%= react_component("CharacterList", { characters: @characters }) %>
  <hr />
  <div class="row">
    <% @characters.each do |character| %>
      <div class="col col-xs-8">
        <h3>Name: <%= link_to character.name, character_path(character) %></h3>
        <p>Race: <%= character.race %></p>
        <p>XP: <%= character.xp %></p>
        <p>Description: <%= character.description %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/characters/new.html.erb
<div class="container">
  <div class="row">
    <div class="col col-xs-auto text-center">
      <h2 class="brand-header">Create Character</h2>
      <%= simple_form_for @character do |f| %>
        <div class="form-inputs">
          <%= f.input :name %>
          <%= f.input :race %>
          <%= f.input :xp %>
          <%= f.input :description %>
        </div>
        <div class="form-actions">
          <%= f.button :submit, 'Save Character', class: 'btn btn-brand btn-lg', id: 'submit-button' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/characters/show.html.erb
<div class="container">
  <div class="row">
    <div class="col col-xs-auto text-center">
      <h1><%= current_character.name %></h1>
      <p>Level: <%= current_character.level %></p>
      <p>Class:
        <% if current_character.levels.exists? %>
          <% current_character.class_levels.each do |key, value| %>
            <br />
            <%= key[:base].to_s + ": " + key[:sub].to_s + " (" + value.to_s + ")" %>
          <% end %>
        <% end %>
      </p>
      <p>Race: <%= current_character.race %></p>
      <p>XP: <%= current_character.xp %></p>
      <p>Description: <%= current_character.description %></p>
      <hr />
      <h2><%= link_to "Add Level", new_character_level_path(current_character) %></h2>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clerical Errors</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'navbar' %>
    <%= render 'flash_messages', flash: flash %>
    <%= yield %>
  </body>
</html>

app/views/levels/new.html.erb
<div class="container">
  <div class="row">
    <div class="col col-xs-auto text-center">
      <h2 class="brand-header">Add Level</h2>
      <hr />
      <h3>Character: <%= current_character.name %></h3>
      <h3>Level: <%= current_character.level + 1 %></h3>
      <hr />

      <%= simple_form_for @level, url: character_levels_path(current_character) do |f| %>
        <div class="form-inputs">
          <%= f.input :base_class %>
          <%= f.input :sub_class %>
        </div>
        <div class="form-actions">
          <%= f.button :submit, 'Add Level', class: 'btn btn-brand btn-lg', id: 'submit-button' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/static_pages/index.html.erb
Hello, world!